monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            gelf:
                type: gelf
                publisher:
                    hostname: '%graylog.hostname%'
                    port: '%graylog.port%'
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            gelf:
                type: gelf
                publisher:
                    hostname: '%graylog.hostname%'
                    port: '%graylog.port%'
                level: warning
                channels: ["!event"]
            stderr:
                type: stream
                path: php://stderr
                level: warning
                formatter: monolog.formatter.json
                channels: ["!event"]
