nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS']
        allow_headers: ['Content-Type', 'Accept', 'X-Requested-With', 'Cache-Control']
        expose_headers: ['Content-Type', 'Cache-Control']
        max_age: 3600
