services:
  mariadb:
    image: mariadb:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: crypto
      MARIADB_USER: db_user_123
      MARIADB_PASSWORD: db_pass_123
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      dockerfile: docker/frankenphp/Dockerfile
      context: .
      target: dev
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .:/app
    environment:
      - APP_ENV=dev
      - CORS_ALLOW_ORIGIN='^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
      - APP_SECRET=
      - DATABASE_URL="mysql://db_user_123:db_pass_123@mariadb:3306/crypto?serverVersion=10.11.2-MariaDB&charset=utf8mb4&collation=utf8mb4_unicode_ci"
    networks:
      - app-network
    depends_on:
      mariadb:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        php bin/console doctrine:database:create --if-not-exists &&
        php bin/console doctrine:migrations:migrate --no-interaction &&
        echo 'Migrations completed. Starting server...' &&
        frankenphp run --config /etc/caddy/Caddyfile.dev
      "

networks:
  app-network:
    driver: bridge
