services:
  api:
    build:
      dockerfile: docker/frankenphp/Dockerfile
      context: .
      target: prod
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env.prod
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/rates/last-24h?pair=EUR/BTC"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  scheduler:
    build:
      dockerfile: docker/frankenphp/Dockerfile
      context: .
      target: prod
    restart: unless-stopped
    command: php bin/console messenger:consume scheduler_default
    env_file:
      - .env.prod
    environment:
      APP_NAME: crypto-rates-scheduler
    networks:
      - app-network
    depends_on:
      api:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
