# Service configuration for Crypto Rates API
# Files in the packages/ subdirectory configure your dependencies.

imports:
    - { resource: parameters.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            # Application parameters
            $appName: '%app.name%'
            $httpDurationBuckets: '%app.http_duration_buckets%'
            $sqlDurationBuckets: '%app.sql_duration_buckets%'
            $binanceApiUrl: '%app.binance_api_url%'
            $binanceKlinesUrl: '%app.binance_klines_url%'
            $supportedPairs: '%app.supported_pairs%'
            $monitoringSkipUrls: '%app.monitoring_skip_urls%'

    # Auto-register services from src/ directory
    App\:
        resource: '../src/'

    App\Service\BinanceApiClientService:
        arguments:
            $httpClient: '@App\Service\TracingHttpClient'

    App\Service\TracingHttpClient:
        arguments:
            $httpClient: '@http_client'

    App\Service\OpenTelemetryService:
        arguments:
            $serviceName: '%otel.service_name%'
            $serviceVersion: '%otel.service_version%'
            $tracesEndpoint: '%otel.exporter_traces_endpoint%'
            $metricsEndpoint: '%otel.exporter_metrics_endpoint%'
            $environment: '%app.environment%'

    App\Tracing\SqlTracingMiddleware:
        tags:
            - { name: 'doctrine.middleware' }

    App\Metrics\SqlMetricsMiddleware:
        tags:
            - { name: 'doctrine.middleware' }

    App\Log\GelfProcessor:
        arguments:
            $serviceName: '%otel.service_name%'
            $environment: '%app.environment%'
        tags:
            - { name: monolog.processor }
